---
notifications:
  email: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib

# Build matrix
os:
- linux
- osx
env:
  global:
  - secure: "H6kgK5KzVP34pId84/GsnLd6Qb2mwYJ3W4tWurK3QetqVh1kH0qC7LOc6gg9ZTIIu750hZDNofl1h7Ttm2jTzfCtAsPdX3wuuBpIi87ZBZY2fwm6zD1anqF0AdKK9IyKYJaSWFjgNzRvzob6VYWxvYFXaKNT948gseuW/f2uSxI="
  matrix:
  - TRAVIS_NODE_VERSION="4" SKIP_LINT="true"
  - TRAVIS_NODE_VERSION="4" SKIP_LINT="true" ARCH="x86"
  - TRAVIS_NODE_VERSION="5" SKIP_LINT="true"
  - TRAVIS_NODE_VERSION="5" SKIP_LINT="true" ARCH="x86"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="6" ARCH="x86"
  - TRAVIS_NODE_VERSION="7"
  - TRAVIS_NODE_VERSION="7" ARCH="x86"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="8" ARCH="x86"
  - TRAVIS_NODE_VERSION="9"
  - TRAVIS_NODE_VERSION="9" ARCH="x86"
  - TRAVIS_NODE_VERSION="10"
matrix:
  exclude:
  - os: osx
    env: TRAVIS_NODE_VERSION="4" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="5" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="6" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="7" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="8" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="9" ARCH="x86"

before_install:

# download node if testing x86 architecture
- nvm install $TRAVIS_NODE_VERSION
- >
  if [[ "$ARCH" == "x86" ]]; then
    BASE_URL=$(node -p "'https://nodejs.org/dist/' + process.version");
    X86_FILE=$(node -p "'node-' + process.version + '-' + process.platform + '-x86'");
    wget $BASE_URL/$X86_FILE.tar.gz;
    tar -xf $X86_FILE.tar.gz;
    nvm deactivate;
    export PATH=`pwd`/$X86_FILE/bin:$PATH;
  fi;

# use g++-4.8 on Linux
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
- $CXX --version

# Cleanup the output of npm
- npm config set progress false
- npm config set spin false

# print versions
- uname -a
- which node; file `which node`
- node --version
- node -p 'process.platform + "@" + process.arch'
- npm --version

# figure out if we should publish
- PUBLISH_BINARY=false
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing native platform Binary Package? ->" $PUBLISH_BINARY

install:
# ensure source install works
- npm install --build-from-source

script:
- if [[ -z "$SKIP_LINT" ]]; then npm run lint; fi
- node ./
- npm test

# if publishing, do it
- >
  if [[ $PUBLISH_BINARY == true ]]; then
    echo "building and uploading binaries"
    npm run prebuild-ci;
  fi;

after_success:
- bash <(curl -s https://codecov.io/bash)
