name: Build
on:
  push:
    tags: '@serialport/bindings@/[1-9]+.[0-9]+.[0-9]+(beta)?'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # https://github.com/nodejs/node-gyp/issues/1663#issuecomment-535049449
    - name: patch node gyp on windows to support Visual Studio 2019
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - name: upgrade npm
      run: npm install -g npm
    - name: npm install
      run: npm install
    - name: npm run prebuild
      run: npm run prebuild
      env:
        prebuild_upload: ${{ secrets.GITHUB_TOKEN }}
